version: '3'

services:
  hdfs-master:
    image: matnar/hadoop   
    container_name: master
    ports:
      - "9870:9870"
      - "54310:54310"
    networks:
      - project1-network
    tty: true
    volumes:
    - ./scripts/hadoop-hdfs:/hdfs-scripts
    depends_on: 
      - hdfs-datanode1
    
  hdfs-datanode1:
    image: matnar/hadoop
    container_name: slave1
    ports:
      - "9864:9864"
    networks:
      - project1-network
    tty: true

  spark-master:
    image: bitnami/spark
    environment:
      - SPARK_MODE=master
    networks:
      - project1-network
    hostname: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    tty: true

  spark-worker:
    image: bitnami/spark
    networks:
      - project1-network
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    tty: true
    depends_on:
      - spark-master

  redis:
    image: redis
    networks:
      - project1-network
    ports:
      - "6379:6379"
    tty: true

networks:
  project1-network:
    driver: bridge
    name: project1-network
