version: '3'

services:
  nifi:
    container_name: nifi-ingestion
    build: ./nifi/nifi-ingestion/
    hostname: nifi-ingestion
    ports:
      - '8443:8443'
    networks:
      - project1-network
    tty: true
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
      - NIFI_HOME=/opt/nifi/nifi-current
    volumes:
      - ./scripts/nifi:/opt/nifi/nifi-current/conf/nifi-ingestion/scripts
      - ./nifi/nifi-ingestion/enc-dataset:/opt/nifi/nifi-current/dataset
    depends_on: 
      - hdfs-master
  
  hdfs-master:
    image: matnar/hadoop   
    container_name: master
    hostname: master
    ports:
      - "9870:9870"
      - "54310:54310"
    networks:
      - project1-network
    tty: true
    volumes:
    - ./scripts/hadoop-hdfs:/hdfs-scripts
    depends_on: 
      - hdfs-datanode1
    
  hdfs-datanode1:
    image: matnar/hadoop
    container_name: slave1
    ports:
      - "9864:9864"
    networks:
      - project1-network
    tty: true

  spark-master:
    image: bitnami/spark
    environment:
      - SPARK_MODE=master
    networks:
      - project1-network
    hostname: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    tty: true

  spark-worker:
    image: bitnami/spark
    networks:
      - project1-network
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    tty: true
    depends_on:
      - spark-master

  redis:
    image: redis
    networks:
      - project1-network
    ports:
      - "6379:6379"
    tty: true

networks:
  project1-network:
    driver: bridge
    name: project1-network
